export enum DashboardsTypes {
  MOST_AVAILABLE_ITEMS = 'DASHBOARD_AVAILABLE_ITEMS',
  PROFITABLE_CRAFTS = 'DASHBOARD_PROFITABLE_CRAFTS',
  PROFITABLE_KNOWN_CRAFTS = 'DASHBOARD_MOST_PROFITABLE_KNOWN_CRAFTS',
  POTENTIAL_DEALS = 'DASHBOARD_POTENTIAL_DEALS',
  CHEAP_BIDS_WITH_LOW_TIME_LEFT = 'DASHBOARD_CHEAP_BIDS_WITH_LOW_TIME_LEFT',
  CHEAP_BIDS = 'DASHBOARD_CHEAP_BIDS',
  CHEAPER_THAN_VENDOR_SELL = 'DASHBOARD_CHEAPER_THAN_VENDOR_SELL',
  TRADE_VENDOR_VALUES = 'DASHBOARD_TRADE_VENDOR_VALUES',
  WATCH_LIST = 'DASHBOARD_WATCH_LIST',
  WATCH_LIST_CRAFTS = 'DASHBOARD_WATCH_LIST_CRAFTS',
  PROSPECTING = 'DASHBOARD_PROSPECTING',
  MILLING = 'DASHBOARD_MILLING',
  // The users pets, that maybe could be sold for something
  POSSIBLE_PROFIT_FROM_PETS = 'DASHBOARD_POSSIBLE_PROFIT_FROM_PETS'
}
